version: '3.8'

services:
    app:
        build:
            context: .
            target: dev
        env_file:
            - .env
        environment:
            NODE_ENV: ${NODE_ENV}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '9229:9229'
        command: ['npm', 'run', 'dev']
